# Configuration for repeated sampling with temperature variation

data:
  input_path: "data/questions.parquet"
  output_path: "data/responses_multi_sample.parquet"
  input_column: "question"
  output_column: "response"
  # Copy additional columns to output
  copy_columns: ["id", "category"]

model:
  url: "http://localhost:8000"

generation:
  # Generate 5 samples per input
  num_samples: 5
  # Use different temperature for each sample
  temperature: [0.5, 0.7, 0.9, 1.0, 1.2]
  top_p: 0.95
  max_tokens: 1024
  stop_sequences: ["###", "END"]
  seed: 42

processing:
  batch_size: 16  # Smaller batch size for multiple samples
  checkpoint_interval: 50

retry:
  max_retries: 5
  retry_delay: 2.0
  timeout: 600

logging:
  level: "INFO"
  file: "logs/repeat_generation.log"
  rotation: "100 MB"
  retention: "7 days"