# Configuration for repeat generation with temperature scheduling
model_config:
  model: "Qwen/Qwen3-8B"
  temperature: 0.6
  top_p: 0.95
  max_tokens: 32768
  gpu_memory_utilization: 0.9

generation_config:
  batch_size: 16
  num_repeats: 5
  repeat_strategy: "temperature_schedule"
  temperature_schedule: [0.5, 0.7, 0.9, 1.1, 1.3]
  seed_increment: 1
  aggregate_responses: true
  aggregation_method: "longest"
  checkpoint_frequency: 50

data_config:
  question_column: "prompt"
  output_format: "nested"
  output_column_prefix: "generation"
  prompt_template: "Question: {question}\n\nAnswer:"
  
parallel_config:
  mode: "single"
  
logging_config:
  level: "INFO"
  save_metadata: true
  track_token_usage: true