# Configuration for parallel processing with data splits
# 
# Usage:
# Process split 1 of 4: vllm-generator generate -c example_split_processing.yaml --split-id 1 --num-splits 4
# Process split 2 of 4: vllm-generator generate -c example_split_processing.yaml --split-id 2 --num-splits 4
# etc.

data:
  input_path: "data/large_dataset.parquet"
  output_path: "data/processed_output.parquet"
  input_column: "prompt"
  output_column: "completion"

model:
  url: "http://localhost:8000"  # Can override with --port 8001 etc.

generation:
  num_samples: 1
  temperature: 0.8
  max_tokens: 2048

processing:
  batch_size: 64
  checkpoint_interval: 100
  # Split configuration can be provided here or via CLI
  # split_id: 1
  # num_splits: 4

retry:
  max_retries: 3
  retry_delay: 1.0
  timeout: 300

logging:
  level: "INFO"
  file: "logs/split_processing.log"