# Simple configuration for basic usage

data:
  input_path: "data/questions.parquet"
  output_path: "data/responses.parquet"
  input_column: "question"
  output_column: "response"

model:
  url: "http://localhost:8000"

generation:
  num_samples: 1
  temperature: 1.0
  max_tokens: 512

processing:
  batch_size: 32

logging:
  level: "INFO"