# Configuration for reasoning models with thinking mode

data:
  input_path: "data/reasoning_problems.parquet"
  output_path: "data/reasoning_solutions.parquet"
  input_column: "problem"
  output_column: "solution"

models:
  - url: "http://localhost:8000"
    name: "qwen3-reasoning"

generation:
  num_samples: 1
  temperature: 0.7
  top_p: 0.8
  top_k: 20
  max_tokens: 8192
  presence_penalty: 1.5
  # Enable thinking mode for reasoning models
  enable_thinking: true
  # Additional parameters via extra_body
  extra_body:
    # Any additional parameters can be added here
    # They will be passed to vLLM's extra_body
    custom_param: "value"

processing:
  batch_size: 8
  num_workers: 1
  checkpoint_interval: 50

retry:
  max_retries: 5
  retry_delay: 2.0
  timeout: 600

logging:
  level: "INFO"
  file: "logs/reasoning_generation.log"